-- MySQL Script generated by MySQL Workbench
-- Thu 27 Apr 2023 10:57:41 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `isMatureContent` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `published_at` DATETIME NOT NULL,
  `isLiked` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comments_users1_idx` ON `mydb`.`comments` (`users_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_comments_games1_idx` ON `mydb`.`comments` (`games_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`consoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`consoles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`consoles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `manufacturer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`consoles_has_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`consoles_has_games` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`consoles_has_games` (
  `consoles_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  PRIMARY KEY (`consoles_id`, `games_id`),
  CONSTRAINT `fk_consoles_has_games_consoles`
    FOREIGN KEY (`consoles_id`)
    REFERENCES `mydb`.`consoles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consoles_has_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_consoles_has_games_games1_idx` ON `mydb`.`consoles_has_games` (`games_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_consoles_has_games_consoles_idx` ON `mydb`.`consoles_has_games` (`consoles_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`discounts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `percentage` INT NOT NULL,
  `from` DATETIME NOT NULL,
  `to` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` DOUBLE NOT NULL,
  `rating` VARCHAR(255) NOT NULL,
  `discounts_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_games_discounts1`
    FOREIGN KEY (`discounts_id`)
    REFERENCES `mydb`.`discounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_games_discounts1_idx` ON `mydb`.`games` (`discounts_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`games_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games_has_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`games_has_categories` (
  `games_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`games_id`, `categories_id`),
  CONSTRAINT `fk_games_has_categories_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_games_has_categories_categories1_idx` ON `mydb`.`games_has_categories` (`categories_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_games_has_categories_games1_idx` ON `mydb`.`games_has_categories` (`games_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`users_has_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_games` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_games` (
  `users_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  `purchased_at` DATETIME NOT NULL,
  `consoles_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `games_id`),
  CONSTRAINT `fk_users_has_games_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_consoles1`
    FOREIGN KEY (`consoles_id`)
    REFERENCES `mydb`.`consoles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_users_has_games_games1_idx` ON `mydb`.`users_has_games` (`games_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_users_has_games_users1_idx` ON `mydb`.`users_has_games` (`users_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_users_has_games_consoles1_idx` ON `mydb`.`users_has_games` (`consoles_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`categories` (`id`, `name`, `isMatureContent`) VALUES (1, 'RPG', false);
INSERT INTO `mydb`.`categories` (`id`, `name`, `isMatureContent`) VALUES (2, 'Gore', true);
INSERT INTO `mydb`.`categories` (`id`, `name`, `isMatureContent`) VALUES (3, 'Slice of life', true);
INSERT INTO `mydb`.`categories` (`id`, `name`, `isMatureContent`) VALUES (4, 'Aventura', false);
INSERT INTO `mydb`.`categories` (`id`, `name`, `isMatureContent`) VALUES (5, 'Accion', false);
INSERT INTO `mydb`.`categories` (`id`, `name`, `isMatureContent`) VALUES (6, 'Anime', false);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`comments`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`comments` (`id`, `users_id`, `games_id`, `comment`, `published_at`, `isLiked`) VALUES (1, 1, 1, 'Se viene Juego del año', '2023-04-27 23:00:00', true);
INSERT INTO `mydb`.`comments` (`id`, `users_id`, `games_id`, `comment`, `published_at`, `isLiked`) VALUES (2, 3, 3, 'Che juego atrae virgenes', '2023-04-27 22:00:00', false);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`consoles`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`consoles` (`id`, `name`, `manufacturer`) VALUES (1, 'Nintendo Switch', 'Nintendo');
INSERT INTO `mydb`.`consoles` (`id`, `name`, `manufacturer`) VALUES (2, 'PS5', 'Sony');
INSERT INTO `mydb`.`consoles` (`id`, `name`, `manufacturer`) VALUES (3, 'Xbox Series S', 'Microsoft');
INSERT INTO `mydb`.`consoles` (`id`, `name`, `manufacturer`) VALUES (4, 'PC', 'PC');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`consoles_has_games`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`consoles_has_games` (`consoles_id`, `games_id`) VALUES (1, 1);
INSERT INTO `mydb`.`consoles_has_games` (`consoles_id`, `games_id`) VALUES (4, 2);
INSERT INTO `mydb`.`consoles_has_games` (`consoles_id`, `games_id`) VALUES (1, 3);
INSERT INTO `mydb`.`consoles_has_games` (`consoles_id`, `games_id`) VALUES (2, 3);
INSERT INTO `mydb`.`consoles_has_games` (`consoles_id`, `games_id`) VALUES (4, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`discounts`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`discounts` (`id`, `name`, `percentage`, `from`, `to`) VALUES (1, 'Descuento Para Chinos', 10, '2023-01-01 00:00:00', '2023-04-30 23:59:59');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`games`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`games` (`id`, `name`, `price`, `rating`, `discounts_id`) VALUES (1, 'The Legend Of Zelda: Tears of the Kingdom', 1600, 'Everyone', NULL);
INSERT INTO `mydb`.`games` (`id`, `name`, `price`, `rating`, `discounts_id`) VALUES (2, 'Team Fortess 2', 100, 'Teen', NULL);
INSERT INTO `mydb`.`games` (`id`, `name`, `price`, `rating`, `discounts_id`) VALUES (DEFAULT, 'Genshin Impact', 0, 'Everyone+10', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`games_has_categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`games_has_categories` (`games_id`, `categories_id`) VALUES (1, 4);
INSERT INTO `mydb`.`games_has_categories` (`games_id`, `categories_id`) VALUES (2, 4);
INSERT INTO `mydb`.`games_has_categories` (`games_id`, `categories_id`) VALUES (3, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`users` (`id`, `username`, `email`, `password`, `fullname`) VALUES (1, 'TomatoPana', 'mdlb.lobo@gmail.com', '12345678', 'Moises David');
INSERT INTO `mydb`.`users` (`id`, `username`, `email`, `password`, `fullname`) VALUES (2, 'Nitto9711', 'janne.oman@gmail.com', '12345678', 'Janne Oman');
INSERT INTO `mydb`.`users` (`id`, `username`, `email`, `password`, `fullname`) VALUES (DEFAULT, 'SuperJacque', 'jaque.lopez@gmail.com', '12345678', 'Jacque');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`users_has_games`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`users_has_games` (`users_id`, `games_id`, `purchased_at`, `consoles_id`) VALUES (1, 1, '2023-04-26 00:00:00', 1);
INSERT INTO `mydb`.`users_has_games` (`users_id`, `games_id`, `purchased_at`, `consoles_id`) VALUES (2, 3, '2023-04-26 00:00:00', 4);
INSERT INTO `mydb`.`users_has_games` (`users_id`, `games_id`, `purchased_at`, `consoles_id`) VALUES (3, 2, '2023-04-26 00:00:00', 4);

COMMIT;

